
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.restaurant;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-26T18:51:04.520+01:00
 * Generated source version: 3.5.11
 *
 */

@javax.jws.WebService(
                      serviceName = "RestaurantServiceImplService",
                      portName = "RestaurantServiceImplPort",
                      targetNamespace = "http://restaurant.example.com/",
                      wsdlLocation = "http://localhost:8080/RestaurantService/services/RestaurantService?wsdl",
                      endpointInterface = "com.example.restaurant.RestaurantService")

public class RestaurantServiceImplPortImpl implements RestaurantService {

    private static final Logger LOG = Logger.getLogger(RestaurantServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.restaurant.RestaurantService#getMenu()*
     */
    public java.util.List<com.example.restaurant.Dish> getMenu() {
        LOG.info("Executing operation getMenu");
        try {
            java.util.List<com.example.restaurant.Dish> _return = new java.util.ArrayList<com.example.restaurant.Dish>();
            com.example.restaurant.Dish _returnVal1 = new com.example.restaurant.Dish();
            _returnVal1.setName("Name-469076739");
            _returnVal1.setPrice(0.9143974388307495);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.restaurant.RestaurantService#placeOrder(java.lang.String arg0)*
     */
    public java.lang.String placeOrder(java.lang.String arg0) {
        LOG.info("Executing operation placeOrder");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-925160126";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
