package com.example.restaurant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-26T18:51:04.543+01:00
 * Generated source version: 3.5.11
 *
 */
@WebServiceClient(name = "RestaurantServiceImplService",
                  wsdlLocation = "http://localhost:8080/RestaurantService/services/RestaurantService?wsdl",
                  targetNamespace = "http://restaurant.example.com/")
public class RestaurantServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://restaurant.example.com/", "RestaurantServiceImplService");
    public static final QName RestaurantServiceImplPort = new QName("http://restaurant.example.com/", "RestaurantServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RestaurantService/services/RestaurantService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RestaurantServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RestaurantService/services/RestaurantService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RestaurantServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RestaurantServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RestaurantServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RestaurantServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RestaurantServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RestaurantServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RestaurantService
     */
    @WebEndpoint(name = "RestaurantServiceImplPort")
    public RestaurantService getRestaurantServiceImplPort() {
        return super.getPort(RestaurantServiceImplPort, RestaurantService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RestaurantService
     */
    @WebEndpoint(name = "RestaurantServiceImplPort")
    public RestaurantService getRestaurantServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RestaurantServiceImplPort, RestaurantService.class, features);
    }

}
