package com.example.restaurant;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.11
 * 2025-03-26T18:51:04.535+01:00
 * Generated source version: 3.5.11
 *
 */
@WebService(targetNamespace = "http://restaurant.example.com/", name = "RestaurantService")
@XmlSeeAlso({ObjectFactory.class})
public interface RestaurantService {

    @WebMethod
    @RequestWrapper(localName = "getMenu", targetNamespace = "http://restaurant.example.com/", className = "com.example.restaurant.GetMenu")
    @ResponseWrapper(localName = "getMenuResponse", targetNamespace = "http://restaurant.example.com/", className = "com.example.restaurant.GetMenuResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.example.restaurant.Dish> getMenu()
;

    @WebMethod
    @RequestWrapper(localName = "placeOrder", targetNamespace = "http://restaurant.example.com/", className = "com.example.restaurant.PlaceOrder")
    @ResponseWrapper(localName = "placeOrderResponse", targetNamespace = "http://restaurant.example.com/", className = "com.example.restaurant.PlaceOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String placeOrder(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
